"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Link from "next/link";
import { trackEvent } from "@/components/PostHogProvider";
import {
  ArrowRight,
  MessageSquare,
  FileText,
  Briefcase,
  BookOpen,
  Shield,
  Scale,
  ChevronRight,
  Plus,
  Sparkles,
  Clock,
  Globe,
  Zap,
} from "lucide-react";
import Footer from "@/components/Footer";

/* ─── Scroll Reveal Hook ──────────────────────────── */
function useReveal() {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          el.classList.add("visible");
          observer.unobserve(el);
        }
      },
      { threshold: 0.15 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return ref;
}

function Reveal({
  children,
  className = "",
  delay = 0,
}: {
  children: React.ReactNode;
  className?: string;
  delay?: number;
}) {
  const ref = useReveal();
  const delayClass = delay > 0 ? `reveal-delay-${delay}` : "";
  return (
    <div ref={ref} className={`reveal ${delayClass} ${className}`}>
      {children}
    </div>
  );
}

/* ─── Typewriter ──────────────────────────────────── */
const verbs = ["Navigate", "Understand", "Defend", "Protect"];

function TypewriterVerb() {
  const [text, setText] = useState("");
  const [verbIndex, setVerbIndex] = useState(0);
  const [charIndex, setCharIndex] = useState(0);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const currentVerb = verbs[verbIndex];
    const timeout = setTimeout(
      () => {
        if (!isDeleting) {
          setText(currentVerb.substring(0, charIndex + 1));
          setCharIndex((c) => c + 1);
          if (charIndex + 1 === currentVerb.length) {
            setTimeout(() => setIsDeleting(true), 2200);
          }
        } else {
          setText(currentVerb.substring(0, charIndex - 1));
          setCharIndex((c) => c - 1);
          if (charIndex - 1 === 0) {
            setIsDeleting(false);
            setVerbIndex((p) => (p + 1) % verbs.length);
          }
        }
      },
      isDeleting ? 50 : 90
    );
    return () => clearTimeout(timeout);
  }, [charIndex, isDeleting, verbIndex]);

  return (
    <span className="gold-text italic">
      {text}
      <span className="inline-block w-[2px] h-[0.85em] bg-gold-400 ml-0.5 align-middle animate-pulse" />
    </span>
  );
}

/* ─── FAQ Accordion ───────────────────────────────── */
const faqs = [
  {
    q: "Is Sidqo a law firm?",
    a: "No. Sidqo is an AI-powered legal information platform for educational purposes. We provide guidance based on UAE federal laws and regulations, but we are not a substitute for licensed legal counsel. For specific legal matters, always consult a qualified UAE attorney.",
  },
  {
    q: "What laws does Sidqo reference?",
    a: "Sidqo is trained on UAE Federal Decree-Law No. 33 of 2021 (Labour Law), the UAE Civil Code, Penal Code, DIFC and ADGM regulations, MOHRE procedures, RERA tenancy laws, and other key federal and emirate-specific legislation.",
  },
  {
    q: "Is my conversation private?",
    a: "Yes. We do not store your conversations, share your data with third parties, or use your queries for training. Your legal questions remain completely confidential.",
  },
  {
    q: "Can I use the legal documents in court?",
    a: "Documents generated by Sidqo are professional templates based on UAE legal standards. While they provide a strong starting point, we recommend having a licensed attorney review any document before official submission or court filing.",
  },
  {
    q: "What if I need a real lawyer?",
    a: "We're building a vetted lawyer marketplace to connect you with licensed UAE attorneys. In the meantime, Sidqo can help you understand your situation, prepare your case, and know the right questions to ask when you do consult a lawyer.",
  },
  {
    q: "How accurate is the AI's legal guidance?",
    a: "Sidqo references specific UAE laws and provides citations where possible. However, law is nuanced and fact-specific. Our AI provides general guidance — not legal advice. Always verify critical legal decisions with a qualified professional.",
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="faq-item">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between py-6 px-2 text-left group"
      >
        <span className="text-[17px] font-display font-semibold text-white/90 group-hover:text-white transition-colors pr-8">
          {q}
        </span>
        <span
          className={`faq-toggle text-white/40 group-hover:text-gold-400 flex-shrink-0 transition-all ${
            open ? "open" : ""
          }`}
        >
          <Plus className="w-5 h-5" />
        </span>
      </button>
      <div className={`faq-content ${open ? "open" : ""}`}>
        <p className="text-[15px] text-white/50 leading-relaxed px-2 pb-6">
          {a}
        </p>
      </div>
    </div>
  );
}

/* ─── Floating Prompt Chips ───────────────────────── */
const floatingPrompts = [
  { text: "My employer hasn't paid me in 3 months", x: "5%", y: "15%", delay: "0s" },
  { text: "Can my company keep my passport?", x: "55%", y: "5%", delay: "2s" },
  { text: "Terminated during probation", x: "10%", y: "70%", delay: "1s" },
  { text: "حقوق نهاية الخدمة", x: "60%", y: "75%", delay: "3s" },
  { text: "Forced to resign — is that legal?", x: "50%", y: "40%", delay: "1.5s" },
];

/* ─── FAQ Schema ─────────────────────────────────── */
const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map(({ q, a }) => ({
    "@type": "Question",
    name: q,
    acceptedAnswer: {
      "@type": "Answer",
      text: a,
    },
  })),
};

/* ─── Page ────────────────────────────────────────── */
export default function HomePage() {
  return (
    <div className="min-h-screen">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      {/* ═══════ HERO ═══════ */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden hero-gradient">
        {/* Subtle geometric pattern */}
        <div className="absolute inset-0 geo-pattern opacity-40" />

        {/* Ambient orbs */}
        <div className="absolute inset-0 overflow-hidden">
          <div className="absolute top-1/4 left-1/4 w-[600px] h-[600px] rounded-full bg-gold-400/[0.04] blur-[120px]" />
          <div className="absolute bottom-1/3 right-1/4 w-[500px] h-[500px] rounded-full bg-teal-500/[0.03] blur-[100px]" />
        </div>

        <div className="relative z-10 max-w-5xl mx-auto px-6 lg:px-8 pt-28 pb-20">
          <div className="text-center">
            {/* Badge */}
            <div className="inline-flex items-center gap-2.5 px-5 py-2.5 rounded-full bg-white/[0.04] border border-white/[0.08] mb-10 animate-fade-in">
              <Sparkles className="w-4 h-4 text-gold-400" />
              <span className="text-sm font-medium text-white/60">
                AI-Powered Legal Guidance for UAE
              </span>
              <div className="w-1.5 h-1.5 rounded-full bg-teal-400 animate-pulse" />
            </div>

            {/* Headline — the most important typography on the page */}
            <h1 className="font-display text-display-lg sm:text-display-xl font-bold mb-8 leading-[1.05] animate-slide-up opacity-0">
              <span className="text-white">Your AI Lawyer</span>
              <br />
              <span className="text-white">to Help You </span>
              <TypewriterVerb />
            </h1>

            {/* Subtitle — one sentence, maximum clarity */}
            <p className="text-lg sm:text-xl text-white/45 mb-12 max-w-2xl mx-auto leading-relaxed font-body animate-slide-up-delay-1 opacity-0">
              Get instant legal guidance based on UAE federal law. Generate
              documents. Build case strategies. Understand your rights.
            </p>

            {/* CTA — single, confident, gold pill */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16 animate-slide-up-delay-2 opacity-0">
              <Link
                href="/chat"
                onClick={() => trackEvent("cta_clicked", { location: "hero", label: "Talk to AI Lawyer" })}
                className="btn-primary flex items-center gap-3 text-[15px] px-8 py-4 group"
              >
                <MessageSquare className="w-4 h-4" />
                Talk to AI Lawyer
                <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
              </Link>
              <Link
                href="/rights"
                className="btn-secondary flex items-center gap-3 text-[15px] px-8 py-4"
              >
                <BookOpen className="w-4 h-4" />
                Know Your Rights
              </Link>
            </div>

            {/* Trust signals — quiet confidence */}
            <div className="flex flex-wrap items-center justify-center gap-x-8 gap-y-3 text-sm text-white/30 animate-slide-up-delay-3 opacity-0">
              {[
                { icon: Shield, text: "UAE Federal Law" },
                { icon: Clock, text: "24/7 Available" },
                { icon: Globe, text: "All 7 Emirates" },
                { icon: Zap, text: "Instant Responses" },
              ].map(({ icon: Icon, text }) => (
                <div key={text} className="flex items-center gap-2">
                  <Icon className="w-3.5 h-3.5 text-gold-400/40" />
                  <span>{text}</span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Scroll hint */}
        <div className="absolute bottom-10 left-1/2 -translate-x-1/2">
          <div className="w-5 h-8 rounded-full border border-white/10 flex items-start justify-center p-1.5">
            <div className="w-1 h-2 rounded-full bg-white/20 animate-bounce" />
          </div>
        </div>
      </section>

      {/* ═══════ SOCIAL PROOF BAR ═══════ */}
      <section className="border-y border-white/[0.04] bg-surface-1/50 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-6 lg:px-8 py-10">
          <Reveal>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
              {[
                { value: "1,500+", label: "UAE Laws Referenced" },
                { value: "24/7", label: "Always Available" },
                { value: "7", label: "Emirates Covered" },
                { value: "< 10s", label: "Avg. Response Time" },
              ].map(({ value, label }) => (
                <div key={label} className="text-center">
                  <div className="text-2xl sm:text-3xl font-display font-bold gold-text mb-1">
                    {value}
                  </div>
                  <div className="text-sm text-white/40">{label}</div>
                </div>
              ))}
            </div>
          </Reveal>
        </div>
      </section>

      {/* ═══════ BENTO — PRODUCT SHOWCASE ═══════ */}
      <section className="py-24 sm:py-32 relative section-gradient">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          {/* Section header */}
          <Reveal>
            <div className="text-center mb-16">
              <p className="text-sm font-semibold text-gold-400 font-display tracking-wide uppercase mb-4">
                Complete Legal Suite
              </p>
              <h2 className="font-display text-display-sm sm:text-display-md font-bold text-white mb-5">
                Everything you need to{" "}
                <span className="gold-text italic">win</span> your case
              </h2>
              <p className="text-lg text-white/40 max-w-2xl mx-auto">
                From understanding your rights to building a complete legal
                strategy — Sidqo guides you every step.
              </p>
            </div>
          </Reveal>

          {/* Bento grid */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
            {/* ── Hero card: AI Chat ── */}
            <Reveal className="lg:col-span-2 lg:row-span-2">
              <div className="bento-card h-full p-8 sm:p-10 relative overflow-hidden group">
                {/* Background glow */}
                <div className="absolute top-0 right-0 w-64 h-64 bg-gold-400/[0.04] blur-[80px] rounded-full" />

                <div className="relative z-10">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 rounded-xl bg-gold-400/10 flex items-center justify-center">
                      <MessageSquare className="w-5 h-5 text-gold-400" />
                    </div>
                    <div>
                      <h3 className="font-display font-bold text-white text-lg">
                        AI Legal Consultation
                      </h3>
                      <p className="text-sm text-white/40">
                        Ask anything about UAE law
                      </p>
                    </div>
                  </div>

                  {/* Mock chat */}
                  <div className="bg-surface-0/60 rounded-2xl p-5 mb-6 border border-white/[0.04]">
                    <div className="space-y-4">
                      <div className="flex gap-3">
                        <div className="w-7 h-7 rounded-full bg-teal-500/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <span className="text-xs text-teal-400">You</span>
                        </div>
                        <div className="bg-white/[0.04] rounded-2xl rounded-tl-md px-4 py-3">
                          <p className="text-sm text-white/70">
                            My employer hasn't paid my salary for 3 months. What
                            are my options under UAE law?
                          </p>
                        </div>
                      </div>
                      <div className="flex gap-3">
                        <div className="w-7 h-7 rounded-full bg-gold-400/20 flex items-center justify-center flex-shrink-0 mt-0.5">
                          <Scale className="w-3.5 h-3.5 text-gold-400" />
                        </div>
                        <div className="bg-gold-400/[0.04] rounded-2xl rounded-tl-md px-4 py-3 border border-gold-400/10">
                          <p className="text-sm text-white/60 leading-relaxed">
                            Under <strong className="text-gold-400">Federal Decree-Law No. 33 of 2021</strong>,
                            you have several strong protections. Your employer is violating the{" "}
                            <strong className="text-gold-400">Wage Protection System (WPS)</strong>.
                            Here are your immediate options...
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Floating prompt chips */}
                  <div className="flex flex-wrap gap-2">
                    {[
                      "Wrongful termination",
                      "Gratuity calculation",
                      "Visa cancellation",
                      "Labour complaint",
                    ].map((prompt) => (
                      <Link
                        key={prompt}
                        href="/chat"
                        className="prompt-chip text-xs"
                      >
                        {prompt}
                      </Link>
                    ))}
                  </div>
                </div>

                {/* Arrow link */}
                <Link
                  href="/chat"
                  className="absolute bottom-8 right-8 w-10 h-10 rounded-full bg-gold-400/10 flex items-center justify-center text-gold-400 opacity-0 group-hover:opacity-100 transition-all hover:bg-gold-400/20"
                >
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </Reveal>

            {/* ── Stat card: Scenarios ── */}
            <Reveal delay={1}>
              <div className="bento-card p-8 relative overflow-hidden">
                <div className="absolute top-0 left-0 w-32 h-32 bg-teal-500/[0.06] blur-[60px] rounded-full" />
                <div className="relative z-10">
                  <div className="w-10 h-10 rounded-xl bg-teal-500/10 flex items-center justify-center mb-5">
                    <FileText className="w-5 h-5 text-teal-400" />
                  </div>
                  <div className="text-4xl font-display font-bold text-white mb-2">
                    50+
                  </div>
                  <p className="text-sm text-white/40 mb-4">
                    Employment scenarios covered, from termination to salary
                    disputes
                  </p>
                  <Link
                    href="/documents"
                    className="inline-flex items-center gap-1.5 text-sm text-teal-400 font-medium hover:text-teal-300 transition-colors"
                  >
                    Generate Documents
                    <ChevronRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            </Reveal>

            {/* ── Stat card: Response time ── */}
            <Reveal delay={2}>
              <div className="bento-card p-8 relative overflow-hidden">
                <div className="absolute bottom-0 right-0 w-32 h-32 bg-gold-400/[0.06] blur-[60px] rounded-full" />
                <div className="relative z-10">
                  <div className="w-10 h-10 rounded-xl bg-gold-400/10 flex items-center justify-center mb-5">
                    <Zap className="w-5 h-5 text-gold-400" />
                  </div>
                  <div className="text-4xl font-display font-bold text-white mb-2">
                    &lt;10s
                  </div>
                  <p className="text-sm text-white/40 mb-4">
                    Average response time with detailed legal citations and
                    references
                  </p>
                  <Link
                    href="/cases"
                    className="inline-flex items-center gap-1.5 text-sm text-gold-400 font-medium hover:text-gold-300 transition-colors"
                  >
                    Build Strategy
                    <ChevronRight className="w-3.5 h-3.5" />
                  </Link>
                </div>
              </div>
            </Reveal>
          </div>

          {/* Feature row — 3 equal cards below */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mt-5">
            {[
              {
                icon: FileText,
                title: "Legal Documents",
                desc: "Demand letters, memorandums, contracts, and court submissions tailored to UAE standards.",
                href: "/documents",
                accent: "teal",
              },
              {
                icon: Briefcase,
                title: "Case Strategy",
                desc: "Complete roadmap: evidence checklist, timeline, legal arguments, and action plan.",
                href: "/cases",
                accent: "gold",
              },
              {
                icon: BookOpen,
                title: "Know Your Rights",
                desc: "Instantly understand your rights in any situation across all areas of UAE law.",
                href: "/rights",
                accent: "teal",
              },
            ].map(({ icon: Icon, title, desc, href, accent }, i) => (
              <Reveal key={title} delay={i + 1}>
                <Link href={href} className="block h-full">
                  <div className="bento-card p-8 h-full group cursor-pointer">
                    <div
                      className={`w-10 h-10 rounded-xl flex items-center justify-center mb-5 ${
                        accent === "gold"
                          ? "bg-gold-400/10"
                          : "bg-teal-500/10"
                      }`}
                    >
                      <Icon
                        className={`w-5 h-5 ${
                          accent === "gold"
                            ? "text-gold-400"
                            : "text-teal-400"
                        }`}
                      />
                    </div>
                    <h3 className="font-display font-bold text-white text-lg mb-2 group-hover:text-gold-400 transition-colors">
                      {title}
                    </h3>
                    <p className="text-sm text-white/40 leading-relaxed mb-4">
                      {desc}
                    </p>
                    <span className="inline-flex items-center gap-1.5 text-sm text-white/30 group-hover:text-gold-400 transition-colors">
                      Explore
                      <ArrowRight className="w-3.5 h-3.5 group-hover:translate-x-0.5 transition-transform" />
                    </span>
                  </div>
                </Link>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════ LEGAL AREAS ═══════ */}
      <section className="py-24 sm:py-32 border-t border-white/[0.04]">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <Reveal>
            <div className="text-center mb-16">
              <h2 className="font-display text-display-sm sm:text-display-md font-bold text-white mb-5">
                All areas of{" "}
                <span className="gold-text italic">UAE law</span>
              </h2>
              <p className="text-lg text-white/40 max-w-xl mx-auto">
                Comprehensive coverage across every legal domain
              </p>
            </div>
          </Reveal>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {[
              { icon: "👔", title: "Employment", desc: "Termination, gratuity, disputes" },
              { icon: "🏢", title: "Business", desc: "Formation, contracts, licensing" },
              { icon: "🏠", title: "Real Estate", desc: "Tenancy, RERA, Ejari" },
              { icon: "👨‍👩‍👧", title: "Family", desc: "Divorce, custody, inheritance" },
              { icon: "⚖️", title: "Criminal", desc: "Rights, procedures, bail" },
              { icon: "✈️", title: "Immigration", desc: "Visas, Golden Visa, permits" },
              { icon: "💼", title: "Debt & Finance", desc: "Cheque cases, restructuring" },
              { icon: "🛡️", title: "Consumer", desc: "Fraud, liability, refunds" },
            ].map(({ icon, title, desc }, i) => (
              <Reveal key={title} delay={Math.min(i + 1, 4)}>
                <Link href="/chat" className="block">
                  <div className="card-surface-interactive p-6 text-center">
                    <div className="text-3xl mb-3">{icon}</div>
                    <h3 className="font-display font-semibold text-white text-sm mb-1">
                      {title}
                    </h3>
                    <p className="text-xs text-white/35">{desc}</p>
                  </div>
                </Link>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════ HOW IT WORKS ═══════ */}
      <section className="py-24 sm:py-32 border-t border-white/[0.04] section-gradient">
        <div className="max-w-5xl mx-auto px-6 lg:px-8">
          <Reveal>
            <div className="text-center mb-20">
              <h2 className="font-display text-display-sm sm:text-display-md font-bold text-white mb-5">
                Get legal help in{" "}
                <span className="gold-text italic">three</span> steps
              </h2>
            </div>
          </Reveal>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-12 md:gap-8 relative">
            {/* Connector line */}
            <div className="hidden md:block absolute top-12 left-[20%] right-[20%] h-px bg-gradient-to-r from-gold-400/20 via-gold-400/40 to-gold-400/20" />

            {[
              {
                step: "01",
                icon: MessageSquare,
                title: "Describe your situation",
                desc: "Tell Sidqo about your legal issue in plain language. No legal jargon needed.",
              },
              {
                step: "02",
                icon: Scale,
                title: "AI analyzes UAE law",
                desc: "Our AI cross-references your situation against 1,500+ UAE federal and local laws.",
              },
              {
                step: "03",
                icon: FileText,
                title: "Get your legal strategy",
                desc: "Receive a complete action plan with documents, timelines, and clear next steps.",
              },
            ].map(({ step, icon: Icon, title, desc }, i) => (
              <Reveal key={step} delay={i + 1}>
                <div className="text-center relative">
                  <div className="relative inline-block mb-8">
                    <div className="w-24 h-24 rounded-3xl bg-surface-1 border border-white/[0.06] flex items-center justify-center mx-auto">
                      <Icon className="w-9 h-9 text-gold-400" />
                    </div>
                    <div className="absolute -top-2 -right-2 w-8 h-8 rounded-full bg-gold-400 text-surface-0 text-xs font-display font-bold flex items-center justify-center">
                      {step.replace("0", "")}
                    </div>
                  </div>
                  <h3 className="font-display font-bold text-white text-lg mb-3">
                    {title}
                  </h3>
                  <p className="text-sm text-white/40 leading-relaxed max-w-xs mx-auto">
                    {desc}
                  </p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ═══════ FAQ ═══════ */}
      <section className="py-24 sm:py-32 border-t border-white/[0.04]">
        <div className="max-w-3xl mx-auto px-6 lg:px-8">
          <Reveal>
            <div className="text-center mb-16">
              <h2 className="font-display text-display-sm sm:text-display-md font-bold text-white mb-5">
                Common questions
              </h2>
              <p className="text-lg text-white/40">
                Everything you need to know about Sidqo
              </p>
            </div>
          </Reveal>

          <Reveal>
            <div className="divide-y divide-white/[0.04]">
              {faqs.map(({ q, a }) => (
                <FAQItem key={q} q={q} a={a} />
              ))}
            </div>
          </Reveal>
        </div>
      </section>

      {/* ═══════ DISCLAIMER ═══════ */}
      <section className="pb-6">
        <div className="max-w-3xl mx-auto px-6 lg:px-8">
          <Reveal>
            <div className="rounded-2xl border border-gold-400/10 bg-gold-400/[0.02] p-6 flex gap-4">
              <Shield className="w-5 h-5 text-gold-400/60 flex-shrink-0 mt-0.5" />
              <div>
                <p className="text-sm font-display font-semibold text-gold-400/80 mb-1.5">
                  Legal Disclaimer
                </p>
                <p className="text-xs text-white/35 leading-relaxed">
                  Sidqo provides AI-powered legal information for educational
                  purposes only. This does not constitute legal advice. For
                  specific legal matters, always consult a licensed attorney
                  qualified to practice in the UAE.
                </p>
              </div>
            </div>
          </Reveal>
        </div>
      </section>

      {/* ═══════ FINAL CTA ═══════ */}
      <section className="py-24 sm:py-32 relative overflow-hidden">
        <div className="absolute inset-0">
          <div className="absolute inset-0 bg-gradient-to-b from-surface-0 via-surface-1 to-surface-0" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gold-400/[0.04] rounded-full blur-[120px]" />
        </div>
        <div className="relative z-10 max-w-3xl mx-auto px-6 lg:px-8 text-center">
          <Reveal>
            <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-gold-400 to-gold-500 flex items-center justify-center mx-auto mb-8 gold-glow">
              <Scale className="w-8 h-8 text-surface-0" />
            </div>
          </Reveal>
          <Reveal delay={1}>
            <h2 className="font-display text-display-sm sm:text-display-md font-bold text-white mb-6">
              Stop guessing.
              <br />
              <span className="gold-text italic">Start knowing.</span>
            </h2>
          </Reveal>
          <Reveal delay={2}>
            <p className="text-lg text-white/40 mb-10 max-w-lg mx-auto">
              Join thousands of UAE residents who navigate legal challenges with
              confidence.
            </p>
          </Reveal>
          <Reveal delay={3}>
            <Link
              href="/chat"
              onClick={() => trackEvent("cta_clicked", { location: "bottom", label: "Start Free Consultation" })}
              className="btn-primary inline-flex items-center gap-3 text-[15px] px-10 py-4 group"
            >
              <MessageSquare className="w-4 h-4" />
              Start Free Consultation
              <ArrowRight className="w-4 h-4 group-hover:translate-x-0.5 transition-transform" />
            </Link>
          </Reveal>
        </div>
      </section>

      <Footer />
    </div>
  );
}
